version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8888:8888"
    environment:
      FLASK_ENV: production
    volumes:
      - .:/app
    command: python run.py 
